# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

abstract_target 'CommonPod' do
#  pod 'RGUIKit', :path => '../../RGUIKit'
  pod 'RGUIKit'
  pod 'AFNetworking'
  
  target 'CampTalk' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for CampTalk
  end
  
  target 'CampTalk Beta' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for CampTalk Beta
  end
end
